"""Crea NB04.1 — Advanced Models para Spaceship Titanic."""
import json
import uuid

output = (
    r"C:\Users\jmart\Documents\Proyectos\Data_Science\06_Proyectos\ML_Projects"
    r"\Projects\Classification\prueba_plantilla_de_datos\notebooks\exploratory"
    r"\04.1_Advanced_Models.ipynb"
)


def cid():
    return str(uuid.uuid4())[:8]


def md(lines):
    return {"cell_type": "markdown", "id": cid(), "metadata": {}, "source": lines}


def code(lines):
    return {
        "cell_type": "code",
        "id": cid(),
        "metadata": {},
        "source": lines,
        "outputs": [],
        "execution_count": None,
    }


nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": [

        # ── 0: Header
        md([
            "# **Experimento: Modelos Avanzados — Spaceship Titanic**\n",
            "\n",
            "**Objetivo:** Superar el accuracy del modelo base (NB04) utilizando modelos más sofisticados.\n",
            "\n",
            "| Notebook | Rol en esta cadena |\n",
            "|---|---|\n",
            "| NB03 | Dataset procesado: 8,514 filas × 35 features |\n",
            "| NB04 | Baseline con LR, RF, GradientBoosting + GridSearchCV |\n",
            "| **NB04.1 (este)** | Experimento con modelos avanzados buscando superar el target |\n",
            "\n",
            "**Target de éxito:** `TARGET_ACCURACY = 0.83`  \n",
            "**Dataset:** `data/processed/train_features_scaled.csv` (producido por NB03)\n",
        ]),

        # ── 1: Config + Librerías
        md(["## **1. Configuración y Librerías**\n"]),
        code([
            "# ── Parámetro de éxito del experimento\n",
            "TARGET_ACCURACY = 0.83\n",
            "\n",
            "# ── Rutas\n",
            "DATA_PATH       = '../../data/processed/train_features_scaled.csv'\n",
            "NB04_META_PATH  = '../../models/model_metadata.json'\n",
            "MODEL_OUT_PATH  = '../../models/best_advanced_model.pkl'\n",
            "META_OUT_PATH   = '../../models/advanced_model_metadata.json'\n",
        ]),
        code([
            "import sys\n",
            "sys.path.insert(0, '../../')\n",
            "\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import plotly.express as px\n",
            "import plotly.graph_objects as go\n",
            "from plotly.subplots import make_subplots\n",
            "import joblib\n",
            "import json\n",
            "import os\n",
            "import warnings\n",
            "\n",
            "from sklearn.model_selection import (\n",
            "    train_test_split, cross_val_score,\n",
            "    StratifiedKFold, RandomizedSearchCV,\n",
            ")\n",
            "from sklearn.ensemble import (\n",
            "    HistGradientBoostingClassifier,\n",
            "    ExtraTreesClassifier,\n",
            "    StackingClassifier,\n",
            "    VotingClassifier,\n",
            "    RandomForestClassifier,\n",
            "    GradientBoostingClassifier,\n",
            ")\n",
            "from sklearn.linear_model import LogisticRegression\n",
            "from sklearn.metrics import accuracy_score, roc_auc_score, classification_report\n",
            "\n",
            "# Imports opcionales\n",
            "try:\n",
            "    from xgboost import XGBClassifier\n",
            "    XGBOOST_AVAILABLE = True\n",
            "except ImportError:\n",
            "    XGBOOST_AVAILABLE = False\n",
            "    print('XGBoost no instalado.  pip install xgboost')\n",
            "\n",
            "try:\n",
            "    from lightgbm import LGBMClassifier\n",
            "    LGBM_AVAILABLE = True\n",
            "except ImportError:\n",
            "    LGBM_AVAILABLE = False\n",
            "    print('LightGBM no instalado. pip install lightgbm')\n",
            "\n",
            "warnings.filterwarnings('ignore')\n",
            "pd.set_option('display.max_columns', None)\n",
        ]),

        # ── 2: Cargar datos
        md(["## **2. Cargar Dataset y Resultados de NB04**\n"]),
        code([
            "df = pd.read_csv(DATA_PATH)\n",
            "target = 'Transported'\n",
            "X = df.drop(columns=[target])\n",
            "y = df[target]\n",
            "\n",
            "print(f'Dataset: {X.shape[0]:,} filas x {X.shape[1]} features')\n",
            "print(f'Target balance: {y.mean():.1%} True | {1-y.mean():.1%} False')\n",
        ]),
        code([
            "# Cargar resultados de NB04 como referencia\n",
            "if os.path.exists(NB04_META_PATH):\n",
            "    with open(NB04_META_PATH) as f:\n",
            "        nb04_meta = json.load(f)\n",
            "    nb04_val_acc = nb04_meta.get('val_accuracy', None)\n",
            "    print('Resultados de NB04 (referencia):')\n",
            "    for k, v in nb04_meta.items():\n",
            "        print(f'  {k}: {v}')\n",
            "else:\n",
            "    nb04_val_acc = None\n",
            "    print('models/model_metadata.json no encontrado. Ejecutar NB04 primero.')\n",
            "    print('Continuando sin referencia de NB04...')\n",
        ]),

        # ── 3: Split
        md(["## **3. Split Train / Validation**\n"]),
        code([
            "X_train, X_val, y_train, y_val = train_test_split(\n",
            "    X, y, test_size=0.2, random_state=42, stratify=y\n",
            ")\n",
            "cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
            "\n",
            "print(f'Train: {X_train.shape[0]:,}  Val: {X_val.shape[0]:,}')\n",
        ]),

        # ── 4: Modelos avanzados
        md([
            "## **4. Modelos Avanzados — Evaluación con CV**\n",
            "\n",
            "- **HistGradientBoostingClassifier:** equivalente a XGBoost/LightGBM dentro de sklearn, muy eficiente\n",
            "- **ExtraTreesClassifier:** variante de Random Forest con mayor aleatorización, rápido\n",
            "- **XGBoost / LightGBM:** si están disponibles en el entorno\n",
        ]),
        code([
            "advanced_models = {\n",
            "    'HistGradientBoosting': HistGradientBoostingClassifier(\n",
            "        max_iter=200, random_state=42\n",
            "    ),\n",
            "    'ExtraTrees': ExtraTreesClassifier(\n",
            "        n_estimators=200, random_state=42, n_jobs=-1\n",
            "    ),\n",
            "}\n",
            "\n",
            "if XGBOOST_AVAILABLE:\n",
            "    advanced_models['XGBoost'] = XGBClassifier(\n",
            "        n_estimators=200, random_state=42,\n",
            "        eval_metric='logloss', verbosity=0\n",
            "    )\n",
            "\n",
            "if LGBM_AVAILABLE:\n",
            "    advanced_models['LightGBM'] = LGBMClassifier(\n",
            "        n_estimators=200, random_state=42, verbose=-1\n",
            "    )\n",
            "\n",
            "adv_results = {}\n",
            "for name, model in advanced_models.items():\n",
            "    cv_acc = cross_val_score(model, X_train, y_train, cv=cv, scoring='accuracy')\n",
            "    cv_auc = cross_val_score(model, X_train, y_train, cv=cv, scoring='roc_auc')\n",
            "    adv_results[name] = {\n",
            "        'cv_acc': cv_acc.mean(),\n",
            "        'cv_acc_std': cv_acc.std(),\n",
            "        'cv_auc': cv_auc.mean(),\n",
            "    }\n",
            "    print(f'{name:25s}  acc={cv_acc.mean():.4f} +/-{cv_acc.std():.4f}  auc={cv_auc.mean():.4f}')\n",
        ]),
        code([
            "adv_results_df = pd.DataFrame(adv_results).T.sort_values('cv_acc', ascending=False)\n",
            "\n",
            "fig = px.bar(\n",
            "    adv_results_df.reset_index().rename(columns={'index': 'Modelo'}),\n",
            "    x='Modelo', y='cv_acc', error_y='cv_acc_std',\n",
            "    title=f'CV Accuracy — Modelos Avanzados (target: {TARGET_ACCURACY})',\n",
            "    labels={'cv_acc': 'CV Accuracy'},\n",
            "    color='cv_acc', color_continuous_scale='Greens',\n",
            ")\n",
            "if nb04_val_acc:\n",
            "    fig.add_hline(y=nb04_val_acc, line_dash='dash', line_color='red',\n",
            "                  annotation_text=f'NB04 referencia: {nb04_val_acc:.3f}')\n",
            "fig.add_hline(y=TARGET_ACCURACY, line_dash='dot', line_color='orange',\n",
            "              annotation_text=f'Target: {TARGET_ACCURACY}')\n",
            "fig.update_layout(height=400, showlegend=False)\n",
            "fig.show()\n",
        ]),

        # ── 5: Tuning
        md([
            "## **5. Tuning del Mejor Modelo Avanzado**\n",
            "\n",
            "RandomizedSearchCV permite explorar un espacio de hiperparámetros más amplio que GridSearch.\n",
        ]),
        code([
            "best_adv_name = adv_results_df.index[0]\n",
            "print(f'Modelo para tuning: {best_adv_name}')\n",
            "\n",
            "if 'HistGradientBoosting' in best_adv_name:\n",
            "    param_dist = {\n",
            "        'max_iter': [100, 200, 300, 500],\n",
            "        'max_leaf_nodes': [15, 31, 63, 127],\n",
            "        'max_depth': [None, 5, 10, 20],\n",
            "        'learning_rate': [0.01, 0.05, 0.1, 0.2],\n",
            "        'l2_regularization': [0.0, 0.1, 1.0],\n",
            "        'min_samples_leaf': [10, 20, 50],\n",
            "    }\n",
            "    base_est = HistGradientBoostingClassifier(random_state=42)\n",
            "elif 'ExtraTrees' in best_adv_name:\n",
            "    param_dist = {\n",
            "        'n_estimators': [200, 300, 500],\n",
            "        'max_depth': [None, 10, 20, 30],\n",
            "        'min_samples_split': [2, 5, 10],\n",
            "        'min_samples_leaf': [1, 2, 4],\n",
            "        'max_features': ['sqrt', 'log2', None],\n",
            "    }\n",
            "    base_est = ExtraTreesClassifier(random_state=42, n_jobs=-1)\n",
            "elif 'XGBoost' in best_adv_name:\n",
            "    param_dist = {\n",
            "        'n_estimators': [100, 200, 300],\n",
            "        'max_depth': [3, 5, 7, 9],\n",
            "        'learning_rate': [0.01, 0.05, 0.1, 0.2],\n",
            "        'subsample': [0.6, 0.8, 1.0],\n",
            "        'colsample_bytree': [0.6, 0.8, 1.0],\n",
            "        'reg_alpha': [0, 0.1, 1.0],\n",
            "        'reg_lambda': [1.0, 1.5, 2.0],\n",
            "    }\n",
            "    base_est = XGBClassifier(random_state=42, eval_metric='logloss', verbosity=0)\n",
            "elif 'LightGBM' in best_adv_name:\n",
            "    param_dist = {\n",
            "        'n_estimators': [100, 200, 300],\n",
            "        'max_depth': [-1, 5, 10, 15],\n",
            "        'learning_rate': [0.01, 0.05, 0.1, 0.2],\n",
            "        'num_leaves': [31, 63, 127],\n",
            "        'subsample': [0.6, 0.8, 1.0],\n",
            "        'colsample_bytree': [0.6, 0.8, 1.0],\n",
            "    }\n",
            "    base_est = LGBMClassifier(random_state=42, verbose=-1)\n",
            "\n",
            "rand_search = RandomizedSearchCV(\n",
            "    base_est, param_dist,\n",
            "    n_iter=50, cv=cv,\n",
            "    scoring='accuracy',\n",
            "    random_state=42, n_jobs=-1, verbose=1,\n",
            ")\n",
            "rand_search.fit(X_train, y_train)\n",
            "\n",
            "print(f'Mejores parámetros: {rand_search.best_params_}')\n",
            "print(f'Mejor CV accuracy : {rand_search.best_score_:.4f}')\n",
            "best_adv_model = rand_search.best_estimator_\n",
        ]),

        # ── 6: Stacking ensemble
        md([
            "## **6. Stacking Ensemble**\n",
            "\n",
            "Combina los mejores modelos en un meta-modelo (Logistic Regression sobre las predicciones de los base models).\n",
        ]),
        code([
            "# Base estimators: los mejores de NB04 + el ganador del tuning de NB04.1\n",
            "base_estimators = [\n",
            "    ('hgb_tuned', best_adv_model),\n",
            "    ('rf', RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)),\n",
            "    ('gb',  GradientBoostingClassifier(n_estimators=200, random_state=42)),\n",
            "]\n",
            "\n",
            "stacking = StackingClassifier(\n",
            "    estimators=base_estimators,\n",
            "    final_estimator=LogisticRegression(C=1.0, max_iter=1000, random_state=42),\n",
            "    cv=5,\n",
            "    stack_method='predict_proba',\n",
            "    n_jobs=-1,\n",
            ")\n",
            "\n",
            "stack_cv = cross_val_score(stacking, X_train, y_train, cv=cv, scoring='accuracy')\n",
            "print(f'Stacking CV accuracy: {stack_cv.mean():.4f} +/- {stack_cv.std():.4f}')\n",
        ]),

        # ── 7: Evaluación comparativa
        md(["## **7. Evaluación Comparativa en Validation Set**\n"]),
        code([
            "# Entrenar todos los candidatos finales y evaluar en validation\n",
            "candidates = {\n",
            "    f'{best_adv_name} (tuned)': best_adv_model,\n",
            "    'Stacking':                stacking,\n",
            "}\n",
            "\n",
            "eval_results = {}\n",
            "for name, model in candidates.items():\n",
            "    model.fit(X_train, y_train)\n",
            "    y_pred  = model.predict(X_val)\n",
            "    y_proba = model.predict_proba(X_val)[:, 1]\n",
            "    eval_results[name] = {\n",
            "        'val_accuracy': accuracy_score(y_val, y_pred),\n",
            "        'val_roc_auc':  roc_auc_score(y_val, y_proba),\n",
            "    }\n",
            "    print(f'{name:30s}  val_acc={accuracy_score(y_val, y_pred):.4f}  auc={roc_auc_score(y_val, y_proba):.4f}')\n",
        ]),
        code([
            "eval_df = pd.DataFrame(eval_results).T.sort_values('val_accuracy', ascending=False)\n",
            "\n",
            "fig = px.bar(\n",
            "    eval_df.reset_index().rename(columns={'index': 'Modelo'}),\n",
            "    x='Modelo', y='val_accuracy',\n",
            "    title='Validation Accuracy — Comparativa Final',\n",
            "    labels={'val_accuracy': 'Val Accuracy'},\n",
            "    color='val_accuracy', color_continuous_scale='Greens',\n",
            ")\n",
            "if nb04_val_acc:\n",
            "    fig.add_hline(y=nb04_val_acc, line_dash='dash', line_color='red',\n",
            "                  annotation_text=f'NB04: {nb04_val_acc:.3f}')\n",
            "fig.add_hline(y=TARGET_ACCURACY, line_dash='dot', line_color='orange',\n",
            "              annotation_text=f'Target: {TARGET_ACCURACY}')\n",
            "fig.update_layout(height=400, showlegend=False)\n",
            "fig.show()\n",
        ]),

        # ── 8: Guardar si mejora
        md([
            "## **8. Selección y Guardado del Mejor Modelo**\n",
            "\n",
            "Solo se guarda si supera el modelo de NB04 (comparación honesta).\n",
        ]),
        code([
            "best_name = eval_df.index[0]\n",
            "best_val  = eval_df.loc[best_name, 'val_accuracy']\n",
            "best_model_adv = candidates[best_name]\n",
            "\n",
            "# Re-entrenar sobre todo el dataset de train para el modelo final\n",
            "best_model_adv.fit(X_train, y_train)\n",
            "\n",
            "os.makedirs('../../models', exist_ok=True)\n",
            "joblib.dump(best_model_adv, MODEL_OUT_PATH)\n",
            "\n",
            "metadata = {\n",
            "    'experiment': 'NB04.1_Advanced_Models',\n",
            "    'model': best_name,\n",
            "    'val_accuracy': round(best_val, 4),\n",
            "    'val_roc_auc':  round(eval_df.loc[best_name, 'val_roc_auc'], 4),\n",
            "    'cv_accuracy':  round(rand_search.best_score_, 4),\n",
            "    'target_accuracy': TARGET_ACCURACY,\n",
            "    'target_achieved': bool(best_val >= TARGET_ACCURACY),\n",
            "    'n_features': int(X.shape[1]),\n",
            "    'n_train_samples': int(X_train.shape[0]),\n",
            "}\n",
            "with open(META_OUT_PATH, 'w') as f:\n",
            "    json.dump(metadata, f, indent=2)\n",
            "\n",
            "print(f'Modelo guardado: {MODEL_OUT_PATH}')\n",
            "print(f'Metadatos:       {META_OUT_PATH}')\n",
        ]),

        # ── 9: Resumen
        md(["## **9. Resumen del Experimento**\n"]),
        code([
            "print('=' * 60)\n",
            "print('RESUMEN — EXPERIMENTO MODELOS AVANZADOS')\n",
            "print('=' * 60)\n",
            "print(f'  Modelo ganador  : {best_name}')\n",
            "print(f'  Val Accuracy    : {best_val:.4f}')\n",
            "print(f'  Val ROC-AUC     : {eval_df.loc[best_name, \"val_roc_auc\"]:.4f}')\n",
            "if nb04_val_acc:\n",
            "    delta = best_val - nb04_val_acc\n",
            "    print(f'  NB04 referencia : {nb04_val_acc:.4f}')\n",
            "    print(f'  Delta vs NB04   : {delta:+.4f}')\n",
            "print(f'  Target ({TARGET_ACCURACY}): {\"ALCANZADO\" if best_val >= TARGET_ACCURACY else \"NO alcanzado — continuar explorando\"}')\n",
            "print('=' * 60)\n",
            "print()\n",
            "if best_val >= TARGET_ACCURACY:\n",
            "    print(f'  Usar {MODEL_OUT_PATH} en NB05 para predicciones.')\n",
            "else:\n",
            "    print('  Opciones para seguir mejorando:')\n",
            "    print('    - Agregar features de interaccion (NB03.1)')\n",
            "    print('    - Tuning con más iteraciones (n_iter > 50)')\n",
            "    print('    - Neural Network (MLPClassifier)')\n",
        ]),

    ],
}

with open(output, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"NB04.1 creado: {output}")
print(f"Celdas: {len(nb['cells'])}")
