"""Modulo de modelos — re-exports de la interfaz publica."""

from src.models.ensembles import build_moe, build_stacking
from src.models.evaluation import (
    analyze_errors,
    compute_oof_metrics,
    evaluate_models,
    evaluate_on_validation,
    optimize_threshold,
)
from src.models.inference import (
    align_features,
    find_model_path,
    generate_submission,
    get_feature_cols,
    load_feature_set_artifacts,
    load_model,
    load_production_feature_set,
    load_val_set,
    preprocess_test,
    save_metadata,
    save_submission,
)
from src.models.tracking import log_metrics_dict, log_params_dict, mlrun, setup_mlflow
from src.models.training import (
    MODELS,
    MOE_BASE_ESTIMATOR,
    PARAM_SPACES,
    CatBoostTuneConfig,
    TuneConfig,
    add_model_prefix,
    make_fold_te_pipeline,
    make_pool,
    oof_proba,
    prefix_param_space,
    tune_model,
)

__all__ = [
    "MODELS",
    "PARAM_SPACES",
    "MOE_BASE_ESTIMATOR",
    "evaluate_models",
    "evaluate_on_validation",
    "compute_oof_metrics",
    "optimize_threshold",
    "TuneConfig",
    "tune_model",
    "build_stacking",
    "build_moe",
    "analyze_errors",
    "make_fold_te_pipeline",
    "prefix_param_space",
    "add_model_prefix",
    "mlrun",
    "setup_mlflow",
    "log_metrics_dict",
    "log_params_dict",
    "CatBoostTuneConfig",
    "make_pool",
    "oof_proba",
    "preprocess_test",
    "generate_submission",
    "save_metadata",
    "save_submission",
    "load_model",
    "find_model_path",
    "load_feature_set_artifacts",
    "load_val_set",
    "get_feature_cols",
    "align_features",
    "load_production_feature_set",
]
